services:
  - type: web
    name: telegram-weather-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    start: uvicorn telegram_weather_bot:app --host 0.0.0.0 --port 10000

    RENDER_EXTERNAL_HOSTNAME=telegram-weather-botq.onrender.com
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8045976543:AAH6sNn08GPdehljiQYWwud_9pPDUFw2FMw"
        sync: false
        key: BOT_TOKEN
        value: "8045976543:AAH6sNn08GPdehljiQYWwud_9pPDUFw2FMw"
        sync: false
        key: OPENWEATHERMAP_API_KEY
        sync: false
        value: "a6115733a483924112f4edb9f3c83482"
      - key: OPENWEATHER_API_KEY
        sync: false
        value: "a6115733a483924112f4edb9f3c83482" 
        key: OPENWEATHER_TOKEN
        sync: false
        value: "a6115733a483924112f4edb9f3c83482"
        key: OWM_API_KEY
        sync: false
        value: "a6115733a483924112f4edb9f3c83482"
        key: OWM_KEY
        sync: false
        value: "a6115733a483924112f4edb9f3c83482" 
      - key: OPENWEATHER_API_KEY
        sync: false
        value: "a6115733a483924112f4edb9f3c83482"
      - key: OWNER_ID
        sync: false
        value: "7749916934"
        key: ADMIN_ID
        sync: false
        value: "7749916934"
        key: RENDER_EXTERNAL_HOSTNAME
        sync: false
        key: telegram-weather-botq.onrender.com
        
        
