services:
  - type: web
    name: weather-bot-final
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
     autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        value: "8045976543:AAFJFSH1kCqp_xKBknv-xNrSPIZLQE3Bpzs"
        sync: false
      - key: OPENWEATHER_TOKEN
        value: "a6115733a483924112f4edb9f3c83482"
        sync: false
      - key: OWNER_ID
        value: "7749916934"
        sync: false
      - key: WEBHOOK_URL
        value: "https://weather-bot-final.onrender.com/webhook/8045976543:AAFJFSH1kCqp_xKBknv-xNrSPIZLQE3Bpzs"
        sync: false
        key: RENDER_EXTERNAL_HOSTNAME
        sync: false
        key: telegram-weather-botq.onrender.com
