services:
  - type: web
    name: telegram-weather-botq
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn telegram_weather_botq:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: BOT_TOKEN
        value: "8045976543:AAFJFSH1kCqp_xKBknv-xNrSPIZLQE3Bpzs"
        sync: false
      - key: OPENWEATHER_TOKEN
        value: "a6115733a483924112f4edb9f3c83482"
        sync: false
      - key: OWNER_ID
        value: "7749916934"
        sync: false
      - key: WEBHOOK_HOST
        value: "https://telegram-weather-botq.onrender.com"
        sync: false
